// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oemqcdwafcgklqppkvqi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9lbXFjZHdhZmNna2xxcHBrdnFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1MjMxNzMsImV4cCI6MjA3NDA5OTE3M30.yMZlrztcIs4QI0ZmIjDN7ZxT-lK9nRcnCMSqE_bMPsI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});